development:
  bucket_name: syahrilpics
  access_key_id: AKIAIMVHT47SL7I3SIOQ
  secret_access_key: 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

test:
  bucket_name: syahrilpics
  access_key_id: AKIAIMVHT47SL7I3SIOQ
  secret_access_key: 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

production:
  bucket_name: syahrilpics
  access_key_id: AKIAIMVHT47SL7I3SIOQ
  secret_access_key: 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